version: '3.9'

services:

  rabbitmq:
    image: 'rabbitmq:3.10-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CLOUDAMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      DEBUG_LOGGER_LEVEL: 'True'
      PORT: 80
    ports:
      - '8080:80'
    volumes:
      - .:/app
    networks:
      - network

networks:
  network: {}